In [1]:
import pandas as pd

In [2]:
df=pd.read_json('/home/pa1/Documents/Hackathon/Hotstar/train_data.json')

In [3]:
df=df.T

In [4]:
df.reset_index(inplace=True)

In [5]:
d1 = df['genres'].apply(lambda st : st.split(','))
x = zip(d1.index,d1.values)
st = []
for i,k in x:
#     print(i,k)
    for j in k:
#         print(j)
        e=(str(df.loc[i,'index'])+' '+j.replace(':',' ')).split(' ')
#         print(e)
#         if len(e) == 4:
#             e[1] = e[1]+ ' ' +e[2]
#             e[2] = e[3]
# #             print(e)
        st.append(e)

In [6]:
df_genres_clean=pd.DataFrame(st)

In [7]:
total_cols=list(df_genres_clean[1].value_counts().index)

In [8]:
sports =[ 'Football', 'Badminton', 'Sport', 'Hockey', 'Kabaddi',
       'Formula1', 'Tennis', 'Athletics', 'Table Tennis', 'FormulaE',
       'Volleyball', 'Boxing', 'Swimming', 'IndiaVsSa']

In [9]:
final_genres=list(set(total_cols)-set(sports))

In [10]:
final_genres.remove('NA')

In [11]:
final_genres.append('sports')

In [13]:
len(final_genres)

22

In [18]:
df_split_genres=df_genres_clean

In [24]:
df_split_genres['sports']=0

In [25]:
df_genres_clean.head()

,0,1,2,3,Drama,Cricket,Wildlife,Family,Crime,Romance,Action,Comedy,LiveTV,TalkShow,Reality,Thriller,sports
0,train-121672,Drama,6,None,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,train-121672,Cricket,3469,None,NaN,3469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,train-121672,Wildlife,79,None,NaN,NaN,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,train-121673,Drama,48949,None,48949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,train-121673,Family,9927,None,NaN,NaN,NaN,9927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [26]:
%%time
for i in range(100):
    if df_genres_clean.loc[i,1]  in final_genres:
        df_split_genres.loc[i,str(df_genres_clean.loc[i,1])]=df_genres_clean.loc[i,2]
#         print(i,df_cities_clean.loc[i,0],df_cities_clean.loc[i,1],df_cities_clean.loc[i,2],'yes')
    else:
        df_split_genres.loc[i,'sports']=int(df_split_genres.loc[i,'sports'])+ int(df_genres_clean.loc[i,2])
#         print(i,df_cities_clean.loc[i,0],df_cities_clean.loc[i,1],df_cities_clean.loc[i,2],'no')

CPU times: user 2.57 s, sys: 156 ms, total: 2.73 s
Wall time: 2.73 s

In [28]:
df_split_genres

,0,1,2,3,Drama,Cricket,Wildlife,Family,Crime,Romance,Action,Comedy,LiveTV,TalkShow,Reality,Thriller,sports,Awards,Travel
0,train-121672,Drama,6,None,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1,train-121672,Cricket,3469,None,NaN,3469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2,train-121672,Wildlife,79,None,NaN,NaN,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
3,train-121673,Drama,48949,None,48949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
4,train-121673,Family,9927,None,NaN,NaN,NaN,9927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
5,train-121673,Crime,1901,None,NaN,NaN,NaN,NaN,1901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
6,train-121673,Romance,16571,None,NaN,NaN,NaN,NaN,NaN,16571,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
7,train-121673,Action,2064,None,NaN,NaN,NaN,NaN,NaN,NaN,2064,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
8,train-121673,Comedy,4225,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4225,NaN,NaN,NaN,NaN,0,NaN,NaN
9,train-121670,Cricket,5715,None,NaN,5715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
10,train-121670,Family,2777,None,NaN,NaN,NaN,2777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
11,train-121670,Drama,20873,None,20873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
12,train-121670,LiveTV,4,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,0,NaN,NaN
13,train-121670,Action,14,None,NaN,NaN,NaN,NaN,NaN,NaN,14,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
14,train-121670,Comedy,15,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,NaN,NaN,NaN,NaN,0,NaN,NaN
15,train-121671,Romance,77,None,NaN,NaN,NaN,NaN,NaN,77,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
16,train-121671,Drama,122,None,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
17,train-121671,Cricket,3883,None,NaN,3883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
18,train-121676,TalkShow,8529,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8529,NaN,NaN,0,NaN,NaN
19,train-121677,TalkShow,5,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,0,NaN,NaN
20,train-121674,Cricket,0,None,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
21,train-121674,Wildlife,21,None,NaN,NaN,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
22,train-121674,Crime,29591,None,NaN,NaN,NaN,NaN,29591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
23,train-121674,Drama,10,None,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
24,train-121674,LiveTV,4,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,0,NaN,NaN
25,train-121674,Comedy,35,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,NaN,NaN,NaN,NaN,0,NaN,NaN
26,train-121675,Romance,724,None,NaN,NaN,NaN,NaN,NaN,724,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
27,train-121675,Cricket,5854,None,NaN,5854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
28,train-121675,Reality,77,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77,NaN,0,NaN,NaN
29,train-121678,Drama,10090,None,10090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665854,train-126320,Sport,554,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665855,train-126320,Documentary,4,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665856,train-126323,Drama,31082,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665857,train-126322,Cricket,450,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665858,train-126322,Kids,6,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665859,train-126322,TalkShow,20,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665860,train-126322,Wildlife,40,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665861,train-126322,Romance,1663,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665862,train-126322,LiveTV,576,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665863,train-126322,Comedy,7712,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665864,train-126325,Cricket,14345,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665865,train-126325,Badminton,97,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665866,train-126325,Reality,69,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665867,train-126325,Crime,249,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665868,train-126324,Cricket,3787,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665869,train-126324,Reality,57,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665870,train-126327,Cricket,5060,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665871,train-126327,Awards,21,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665872,train-126327,Crime,1872,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665873,train-126326,Drama,25428,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665874,train-126326,Family,7,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665875,train-126329,Drama,50749,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665876,train-126329,Romance,9,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665877,train-126328,Cricket,17417,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665878,train-126328,Reality,14947,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665879,train-126328,Drama,14565,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665880,train-126328,LiveTV,1662,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665881,train-126328,Awards,640,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665882,train-126328,Action,41,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
665883,train-126328,Thriller,6,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN

In [29]:
%%time
for i in range(1000):
    if df_genres_clean.loc[i,1]  in final_genres:
        df_split_genres.loc[i,str(df_genres_clean.loc[i,1])]=df_genres_clean.loc[i,2]
#         print(i,df_cities_clean.loc[i,0],df_cities_clean.loc[i,1],df_cities_clean.loc[i,2],'yes')
    else:
        df_split_genres.loc[i,'sports']=int(df_split_genres.loc[i,'sports'])+ int(df_genres_clean.loc[i,2])
#         print(i,df_cities_clean.loc[i,0],df_cities_clean.loc[i,1],df_cities_clean.loc[i,2],'no')

CPU times: user 22.6 s, sys: 566 ms, total: 23.2 s
Wall time: 23.2 s

In [34]:
print(i)

999

In [37]:
df_split_genres.shape

(665884, 25)

In [39]:
df_split_genres.iloc[665883,:]

0            train-126328
1                Thriller
2                       6
3                    None
Drama                 NaN
Cricket               NaN
Wildlife              NaN
Family                NaN
Crime                 NaN
Romance               NaN
Action                NaN
Comedy                NaN
LiveTV                NaN
TalkShow              NaN
Reality               NaN
Thriller              NaN
sports                  0
Awards                NaN
Travel                NaN
Teen                  NaN
Mythology             NaN
Kids                  NaN
Science               NaN
Horror                NaN
Table                 NaN
Name: 665883, dtype: object

In [ ]:
# %%time
# for i in range(665883):
#     if df_genres_clean.loc[i,1]  in final_genres:
#         df_split_genres.loc[i,str(df_genres_clean.loc[i,1])]=df_genres_clean.loc[i,2]
# #         print(i,df_cities_clean.loc[i,0],df_cities_clean.loc[i,1],df_cities_clean.loc[i,2],'yes')
#     else:
#         df_split_genres.loc[i,'sports']=int(df_split_genres.loc[i,'sports'])+ int(df_genres_clean.loc[i,2])
# #         print(i,df_cities_clean.loc[i,0],df_cities_clean.loc[i,1],df_cities_clean.loc[i,2],'no')

In [41]:
df_split_genres.to_csv('Hotstar_Genres_split&clean.csv')